spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  datasource:
    url: jdbc:h2:file:~/workout_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update